testproject/book/urls.py
from django.contrib import admin
from django.urls import path ,re_path ,include
from . import views



urlpatterns = [
    path('', views.index , name = 'index'),
    path('<slug:slug>/', views.detail, name='detail'),
    # path('detail/<slug:slug>/', views.detail, name='detail'),
   
]

testproject/myapp/urls.py
from django.contrib import admin
from django.urls import path ,re_path
from . import views

urlpatterns = [
    # path('hello/<int:id>', views.hello ,name = 'hello'),
    path('hello/<int:id>', views.hello ,name = 'hello'),
    path('', views.index ,name = 'witaya'),
    re_path(r'article/(?P<year>[0-9]{4})$',views.article),
    re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)/$',views.article , name='article'),
]

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path ,re_path ,include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('myapp.urls','myapp'),namespace ='myapp')),
    path('book/', include(('book.urls','book'),namespace ='book')),
#     re_path(r'article/(?P<year>[0-9]{4})$',views.article),
#     re_path(r'article/(?P<year>[0-9]{4})/(?P<slug>[\w-]+)/$',views.article , name='article'),
    
]
# +static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

if settings.DEBUG :
    #static/media
    urlpatterns+=static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)

testproject/book/models.py
from django.db import models
from django.utils.html import format_html


BOOK_LEVEL_CHOICE = (
('Evaluation','Evaluation'),
('Design','Design'),
('Implementation','Implementation'),
('ECN under review','ECN under review'),

)






class Author(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'ผู้เเต่ง'

    def __str__(self) -> str:
        """Return a string representation of the author's name."""
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural = 'หมวดหมู่'

    def __str__(self):
        return self.name


class Book(models.Model):
    code = models.CharField(max_length=10, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    name = models.CharField(max_length=10, unique=True)
    description = models.TextField(null=True, blank=True)
    # Category is one but book is many
    category = models.ForeignKey (Category , null=True ,blank = True ,on_delete=models.CASCADE)
    # need only blank = True  , null noneed because it is many to many
    author = models.ManyToManyField (Author ,blank = True)
    level = models.CharField (max_length=20 ,null=True ,blank = True , choices=BOOK_LEVEL_CHOICE)
    image = models.FileField(upload_to = 'upload', null=True ,blank = True)
    # image2 = models.FileField(upload_to = 'upload', null=True ,blank = True)
    price = models.FloatField(default=0)
    # status = models.CharField (max_length=10 ,null=True ,blank = True , choices=BOOK_STATUS)
    published = models.BooleanField(default=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)




    class Meta:
        verbose_name_plural = 'หนังสือ'
        ordering = ['-create']

    def __str__(self):
        return self.name

    def show_image(self):
        if self.image:
            return format_html ( '<img src= "%s"   +  height ="50px">'   %self.image.url )
        return ''
    show_image.allow_tags = True
    show_image.short_descripttion = 'Image'


    def get_comment_count(self):
        return self.bookcomment_set.count() 



class BookComment(models.Model):
    book = models.ForeignKey (Book  ,on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    rating = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now= True)
    
    class Meta:
        verbose_name_plural = 'BookComment'
        ordering = ['id']


    def __str__(self):
        return self.comment

testproject/myapp/models.py
from django.db import models

# Create your models here.

testproject/book/views.py
from django.shortcuts import render ,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category ,Book ,BookComment



def index(request):
    categ_id = request.GET.get('categoryid')  # Get the category ID from the query parameter
    print(categ_id)
    categories = Category.objects.all()  # Fetch all categories
    books = Book.objects.filter(category_id=categ_id) if categ_id else Book.objects.all()
   
    # if categ_id:
    #     books = Book.objects.filter(category_id=categ_id)
    # else:
    #     books = Book.objects.all()



    
    paginator = Paginator(books ,8)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages) 

    

    
    
    return render(request, 'book/index.html', {
        'categories': categories,
        'books': books,
        'categ_id': int(categ_id) if categ_id else None  # Pass the category ID to the template
    })





def detail(request, slug):
    # Fetch the book using the slug
    book = get_object_or_404(Book, slug=slug)
    # Fetch comments using the related_name
    comments = book.bookcomment_set.all()
    return render(request, 'book/detail.html', {'book': book , 'comments': comments})

testproject/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def hello(request,id):
    # greeting = "your ID : {000}".format(id)
    greeting = f"your ID is == {id}"
    return HttpResponse(greeting)


def article(request,year,slug):
    # greeting = "your ID : {000}".format(id)

    return HttpResponse(f"<h1>Witaya Chaison {year} {slug}</h1>")


def index(request):
    id ='001'
    name = 'Witaya'
    email ='witaya.chaison@gmail.com'
    
    activities = [ 'Football' , 'Running' ,'Badminton']


    # greeting = "your ID : {000}".format(id)
    return render(request, "index.html" ,{

    'id1' : id ,
    'name1' : name ,
    'email1' : email,
    'activities':   activities

    })

testproject/templates/book/detail.html
{%load humanize %}  <!-- This loads the humanize template tag library for formatting numbers. -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{{ book.name }}</title>
    <!-- Link to Bootstrap CSS for styling -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    />

    <style>
      .image-container {
        position: relative;
        overflow: hidden; /* Prevent image from overlapping */
        width: 50%; /* Ensure it fits within the column */
        height: auto;
      }

      .hover-image {
        width: 80%; /* Make the image responsive */
        height: auto;
        transition: transform 0.3s ease-in-out; /* Smooth scaling effect */
      }

      .hover-image:hover {
        transform: scale(1.1); /* Enlarge the image slightly on hover */
      }
    </style>
  </head>

  <body>
    <div class="container mt-5">
      <!-- Book Details Section -->
      <div class="row">
         
        <div class="col-lg-4 col-md-6 image-container" >
                 <img src="{{ book.image.url }}" alt="{{ book.name }}" class="hover-image img-fluid rounded" loading="lazy">
        </div> 

      

        <div class="col-lg-8 col-md-6">
          <h3>{{ book.name }}</h3>
          <table class="table table-bordered table-striped">
            <tbody>
              <!-- Book Name -->
              <tr>
                <th>M/C</th>
                <td>{{ book.name }}</td>
              </tr>
              <tr>
                <th>TDR/ECN</th>
                <td>{{ book.code }}</td>
              </tr>
              <!-- Book Category -->
              <tr>
                <th>Category</th>
                <td>{{ book.category.name }}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{{ book.level }}</td>
              </tr>

            
              <tr>
                <th>Description</th>
                <td>{{ book.description }}</td>
              </tr>
            </tbody>
          </table>
          <hr />
        </div>
      
    </div>
      <hr />



      <h3 class="mt-5">Update : [ {{book.get_comment_count}} items ]</h3>
      <hr />

      <div>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Date</th>
              <th>Datails</th>
              <th>Who</th>
            </tr>
          </thead>
          <tbody>
            {% for comment in comments %}
            <tr>
              <td>{{ comment.updated }}</td>
              <td>{{ comment.comment }}</td>
              <td>{{ comment.author }}</td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="2" class="text-center">No comments yet.</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

testproject/templates/book/index.html
{% extends 'layout/base.html'%} {% load static %}
{% load humanize %} 


<title>{%block title%} Book Page {%endblock%}</title>

{%block content%}

<div class="row">
  <div class="col-lg-2">
    <div class="list-group text-center">
      <!-- Highlight "ALL" if no category is selected -->
      <a
        href="{% url 'book:index' %}"
        class="list-group-item list-group-item-action {% if not categ_id %} active {% endif %}"
      >
        ALL
      </a>
      <!-- Loop through categories and highlight the active one -->
      {% for c in categories %}
      <a
        href="{% url 'book:index' %}?categoryid={{ c.id }}"
        class="list-group-item list-group-item-action {% if categ_id == c.id %} active {% endif %}"
      >
        {{ c.name }}
      </a>
      {% endfor %}
    </div>
  </div>

  <div class="col-lg-10">
    <h1>FOF Contamination update</h1>

    <div class="row mt-1">
      {% for b in books %}
      <div class="col-lg-3 mt-4">
        <div class="card">
          {% if b.image %}
          <a href="{% url 'book:detail'  slug=b.slug %}">
            <div class="image-container">
              <img
                class="card-img-top img-fluid"
                src="{{b.image.url}}"
                alt=""
              />
            </div>
          </a>
          {% endif %}

          <div class="card-body">
            <h5>
              <a href="{% url 'book:detail'  slug=b.slug %}">{{b.name}}</a>
            </h5>
          </div>
          <div>&nbsp&nbspCategory: {{b.category.name}}</div>
          <!-- <div>&nbsp&nbspPrice: {{b.price|floatformat:2|intcomma}}</div> -->
          {% for a in b.author.all %}
          <div>
            &nbsp&nbspEngineer:
            <span class="badge badge-secondarey">{{a.name}}</span>
          </div>
          {% endfor %}

          <a
            href="{% url 'book:detail'  slug=b.slug %}"
            class="btn btn-secondary mt-3 " 
          >
            More Detail</a
          >
        </div>
      </div>

      {% endfor %}
    </div>

    <hr />

    <ul class="pagination justify-content-center mb-5">
      <!-- Previous Page Link -->
      {% if books.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ books.previous_page_number }}"
          >Previous</a
        >
      </li>
      {% endif %}

      <!-- Page Numbers -->
      {% for i in paginator.page_range %}
      <li class="page-item {% if books.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
      {% endfor %}

      <!-- Next Page Link -->
      {% if books.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ books.next_page_number }}">Next</a>
      </li>
      {% endif %}
    </ul>
  </div>

  {%endblock%}
</div>

testproject/templates/index.html
{% extends  'layout/base.html'%} 



{%block content%} 
<h1>Your register Page is</h1>
<h1>The id is = {{id1}}</h1>
<h1>{{email1}}</h1>
<h1>{{name1}}</h1>

{% if id1 == '001' and name1 == 'Witaya'%}
<h2>Access Complete {{name1}}</h2>

{%else%}

<h2>Tay again</h2>

{%endif%}

<ul>
    {% for a in activities%}
    <li>{{a}}</li>
    
    {%endfor%}
</ul>


<a href = "{% url 'myapp:hello' id=1 %}">Go to Hellow_ID 1</a><br>
<a href = "{% url 'myapp:witaya' %}">Go to This Home</a><br>
<a href = "{% url 'myapp:article' year=2000  slug='witaya-chaison'%}">Go to Article with Slug</a><br>
<a href = "{% url 'book:index' %}">Go to Book_Store</a><br>



{% endblock %} 

testproject/templates/layout/base.html
               
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="styles.css"> -->
    <title>{%block title%}  Main Page  {%endblock%}</title>
    <style>
    .image-container {
      position: relative;
      width: 100%;
      padding-top: 75%; /* 4:3 aspect ratio (adjust as needed) */
      overflow: hidden;
    }
    
    .image-container img {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      object-fit: cover; /* Ensures the image fills the container while maintaining its aspect ratio */
    }
    
    .card {
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      height: 100%; /* Ensures all cards are the same height */
    }

    </style>


  </head>
  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">FOF Contamination</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Home</a>
        <a class="p-2 text-dark" href="#">ADSI</a>
        <a class="p-2 text-dark" href="#">BUD</a>
        <a class="p-2 text-dark" href="#">Balance</a>
        <a class="p-2 text-dark" href="#">Fitting</a>
        <a class="p-2 text-dark" href="#">Cover</a>

      </nav>
      <a class="btn btn-outline-primary mx-2" href="#">Sign up</a>
      <a class="btn btn-outline-danger" href="#">Log in</a>
    </div>
    


    <div class="container-fluid">

  
      {%block content%}  putdata here  {%endblock%}
      
      
      
    </div>
 
  
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    
  </body>
</html>

testproject/templates/layout/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">
  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-white"
          style="background-color: #929fba"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer
              content. Lorem ipsum dolor sit amet, consectetur adipisicing
              elit.
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
            <p>
              <a class="text-white">MDBootstrap</a>
            </p>
            <p>
              <a class="text-white">MDWordPress</a>
            </p>
            <p>
              <a class="text-white">BrandFlow</a>
            </p>
            <p>
              <a class="text-white">Bootstrap Angular</a>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>

            <!-- Facebook -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #3b5998"
               href="#!"
               role="button"
               ><i class="fab fa-facebook-f"></i
              ></a>

            <!-- Twitter -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #55acee"
               href="#!"
               role="button"
               ><i class="fab fa-twitter"></i
              ></a>

            <!-- Google -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #dd4b39"
               href="#!"
               role="button"
               ><i class="fab fa-google"></i
              ></a>

            <!-- Instagram -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #ac2bac"
               href="#!"
               role="button"
               ><i class="fab fa-instagram"></i
              ></a>

            <!-- Linkedin -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #0082ca"
               href="#!"
               role="button"
               ><i class="fab fa-linkedin-in"></i
              ></a>
            <!-- Github -->
            <a
               class="btn btn-primary btn-floating m-1"
               style="background-color: #333333"
               href="#!"
               role="button"
               ><i class="fab fa-github"></i
              ></a>
          </div>
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div
         class="text-center p-3"
         style="background-color: rgba(0, 0, 0, 0.2)"
         >
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/"
         >MDBootstrap.com</a
        >
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->